GET http://localhost:3000/users/userhome

###

GET http://localhost:3000/users/

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"fulano.detal",
    "email":"fulano@detal.com",
    "password":"password"
}

###

GET http://localhost:3000/users/62baf41abe70613c3f4be5a4

###

PATCH http://localhost:3000/users/62baf41abe70613c3f4be5a4
Content-Type: application/json

{
    "name":"Jirão"
}

###

DELETE http://localhost:3000/users/62b8c3ae37e00164124fbce4

###

POST http://localhost:3000/users/62b8c558dbc6498c89986a95

{
    
}
